language: go

go:
    - 1.2

install:
    - go get github.com/smartystreets/goconvey
    - go get github.com/jacobsa/oglematchers
    - go get github.com/stretchr/testify
    - go get code.google.com/p/go.tools/cmd/cover
    - go build

script:
    - go test -covermode=count -coverprofile=profile.cov
    - go get github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin/
    - goveralls -coverprofile=profile.cov -service=travis-ci
